In [1]:
import numpy as np

FEEDFORWARD TEST

In [2]:
x=np.random.random((3,1))
print(x)

[[0.05201972]
 [0.43663601]
 [0.46440448]]


In [3]:
w_ih=np.random.random((4,3))
print(w_ih)

[[0.53379214 0.41103896 0.59605825]
 [0.58532877 0.64058598 0.899485  ]
 [0.78327735 0.32654234 0.40133037]
 [0.55356614 0.99012117 0.98033167]]


In [4]:
h=w_ih@x
print(h)

[[0.48405425]
 [0.72787641]
 [0.36970563]
 [0.91638934]]


In [5]:
h+=3 #bias
print(h)

[[3.48405425]
 [3.72787641]
 [3.36970563]
 [3.91638934]]


In [6]:
def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

In [7]:
H=sigmoid(h)
print(H)

[[0.97023064]
 [0.97652069]
 [0.96674423]
 [0.98047592]]


In [8]:
w_ih=np.random.random((1,4))
print(w_ih)

[[0.70291005 0.84330852 0.04018599 0.13123722]]


In [9]:
out=w_ih@H
out+=3 #bias
print(out)

[[4.6730176]]


BACKPROPAGATION TEST

In [11]:
y= np.reshape([1,0,0],(3,1))
print(y)

[[1]
 [0]
 [0]]


In [14]:
i =np.random.random((20,1))
print(i)

[[0.88708719]
 [0.53711186]
 [0.66419022]
 [0.25976461]
 [0.80153545]
 [0.881101  ]
 [0.12116121]
 [0.21869726]
 [0.90214645]
 [0.78447698]
 [0.80158004]
 [0.0626105 ]
 [0.17960762]
 [0.82873028]
 [0.77132552]
 [0.82265816]
 [0.9437693 ]
 [0.95087923]
 [0.10060444]
 [0.0927141 ]]
